#!/bin/bash

#1-preparation of the VM 
 swapoff -a
 echo "net/bridge/bridge-nf-call-ip6tables = 1" >> /etc/ufw/sysctl.conf
 echo "net/bridge/bridge-nf-call-iptables = 1" >> /etc/ufw/sysctl.conf
 echo "net/bridge/bridge-nf-call-arptables = 1" >> /etc/ufw/sysctl.conf

 sudo apt-get install -y ebtables ethtool

#docker installation installation 
if [ -x "$(command -v docker)" ]; then
    echo "docker is installed"
    
else
    echo "Installation of docker"
   sudo  apt-get update
   sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
   sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  #to test if docker works correctly run 
  #sudo docker run hello-world

fi

#install kubelet kubeadm kubectl
 
 curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
 cat <<EOF >/etc/apt/sources.list.d/kubernetes.list 
  deb https://apt.kubernetes.io/ kubernetes-xenial main 
EOF
 
 apt-get update
 apt-get install -y kubelet kubeadm kubectl
 apt-mark hold kubelet kubeadm kubectl
 
